[package]
name = "ciuc_ap_2025"
version = "0.1.0"
edition = "2024"

[dependencies]
common-game = { path = "../common/app/game" }
crossbeam-channel = "0.5.15"



[[bin]]
name = "Ciuc_ap_2025"
path = "./src/main.rs"
