[package]
name = "ciuc_planet"
version = "0.1.0"
edition = "2024"

[dependencies]
common-game = { git = "https://github.com/unitn-ap-2025/common.git", branch = "main" }
crossbeam-channel = "0.5.15"


